//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taller_informaticaEntities5 : DbContext
    {
        public taller_informaticaEntities5()
            : base("name=taller_informaticaEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<curso> cursos { get; set; }
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<loginUsuario> loginUsuarios { get; set; }
        public virtual DbSet<modulo> modulos { get; set; }
        public virtual DbSet<profesore> profesores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tallere> talleres { get; set; }
        public virtual DbSet<curso_horario> curso_horario { get; set; }
        public virtual DbSet<curso_modulo> curso_modulo { get; set; }
        public virtual DbSet<Est_prof> Est_prof { get; set; }
        public virtual DbSet<modulo_hora> modulo_hora { get; set; }
        public virtual DbSet<prof_curso> prof_curso { get; set; }
        public virtual DbSet<prof_modulo> prof_modulo { get; set; }
        public virtual DbSet<prof_taller> prof_taller { get; set; }
    }
}
