//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_prof
    {
        public int Id_Est_prof { get; set; }
        public Nullable<int> profesor_id { get; set; }
        public Nullable<int> estudiantes_id { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual profesore profesore { get; set; }
    }
}
