//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estudiante()
        {
            this.Est_prof = new HashSet<Est_prof>();
        }
    
        public int id_estu { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<long> cedula { get; set; }
        public string nacionalidad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string tipo_sangre { get; set; }
        public string grado { get; set; }
        public string status { get; set; }
        public Nullable<int> id_taller { get; set; }
        public Nullable<int> id_curso { get; set; }
        public Nullable<int> id_modulo { get; set; }
    
        public virtual curso curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Est_prof> Est_prof { get; set; }
        public virtual modulo modulo { get; set; }
        public virtual tallere tallere { get; set; }
    }
}
