//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prof_modulo
    {
        public int Id_prof_modulo { get; set; }
        public Nullable<int> prof_id { get; set; }
        public Nullable<int> modulo_id { get; set; }
    }
}
